# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 9001
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
        file-extension: yml
        namespace: 7d3e5f19-a102-471a-b6e0-67bd7d1d35f3
        group: USER_GROUP
      discovery:
          server-addr: localhost:8848
          namespace: 7d3e5f19-a102-471a-b6e0-67bd7d1d35f3

management:
  endpoints:
    web:
      exposure:
        include: '*'


